# 1. Importing  packages and datasets

In [2]:
import pandas as pd
import numpy as np
import math as math
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.feature_selection import VarianceThreshold
from sklearn.linear_model import LinearRegression

In [3]:
# method for vizualization dataframes

def color_false_red(val):
    if val == False:
        color = 'red'
    else:
        color = 'green'
    return 'color: %s' % color

In [4]:
# method for vizualization dataframes

def highlight(x):
    c1 = 'color: green'
    c2 = 'color: red'
    c3 = '' 
    #m = x.eq(x.iloc[:, 0], axis=0)
    m = x != True
    n = x != False
    df1 = pd.DataFrame(c3, index=x.index, columns=x.columns)
    #add color red by False values 
    df1 = df1.where(m, c1)
    df1 = df1.where(n, c2)
    return df1

In [5]:
# importing datasets

key_stats = pd.read_csv('D:/Luka Sve/Strucni radovi/DEA/Nova baza fudbalera/key_stats.csv')
goals = pd.read_csv('D:/Luka Sve/Strucni radovi/DEA/Nova baza fudbalera/goals.csv')
goalkeeping = pd.read_csv('D:/Luka Sve/Strucni radovi/DEA/Nova baza fudbalera/goalkeeping.csv')
distributon = pd.read_csv('D:/Luka Sve/Strucni radovi/DEA/Nova baza fudbalera/distributon.csv')
disciplinary = pd.read_csv('D:/Luka Sve/Strucni radovi/DEA/Nova baza fudbalera/disciplinary.csv')
defending = pd.read_csv('D:/Luka Sve/Strucni radovi/DEA/Nova baza fudbalera/defending.csv')
attempts = pd.read_csv('D:/Luka Sve/Strucni radovi/DEA/Nova baza fudbalera/attempts.csv')
attacking = pd.read_csv('D:/Luka Sve/Strucni radovi/DEA/Nova baza fudbalera/attacking.csv')

In [6]:
# Combining and merging 3 attributes in one, in order to make unique index for player

key_stats['key'] = key_stats[['player_name', 'club', 'position']].agg('-'.join, axis=1)
goals['key'] = goals[['player_name', 'club', 'position']].agg('-'.join, axis=1)
goalkeeping['key'] = goalkeeping[['player_name', 'club', 'position']].agg('-'.join, axis=1)
distributon['key'] = distributon[['player_name', 'club', 'position']].agg('-'.join, axis=1)
disciplinary['key'] = disciplinary[['player_name', 'club', 'position']].agg('-'.join, axis=1)
defending['key'] = defending[['player_name', 'club', 'position']].agg('-'.join, axis=1)
attempts['key'] = attempts[['player_name', 'club', 'position']].agg('-'.join, axis=1)
attacking['key'] = attacking[['player_name', 'club', 'position']].agg('-'.join, axis=1)

In [7]:
key_stats = key_stats.set_index('key')
goals = goals.set_index('key')
goalkeeping = goalkeeping.set_index('key')
distributon = distributon.set_index('key')
disciplinary = disciplinary.set_index('key')
defending = defending.set_index('key')
attempts = attempts.set_index('key')
attacking = attacking.set_index('key')

In [8]:
goals.drop('serial', axis=1,inplace=True)
goals.drop('position', axis=1,inplace=True)
goals.drop('goals', axis=1,inplace=True)
goals.drop('match_played', axis=1,inplace=True)
goals.drop('club', axis=1,inplace=True)
goals.drop('player_name', axis=1,inplace=True)

In [9]:
goalkeeping.drop('serial', axis=1,inplace=True)
goalkeeping.drop('club', axis=1,inplace=True)
goalkeeping.drop('position', axis=1,inplace=True)
goalkeeping.drop('match_played', axis=1,inplace=True)
goalkeeping.drop('player_name', axis=1,inplace=True)

In [10]:
distributon.drop('serial', axis=1,inplace=True)
distributon.drop('club', axis=1,inplace=True)
distributon.drop('position', axis=1,inplace=True)
distributon.drop('match_played', axis=1,inplace=True)
distributon.drop('player_name', axis=1,inplace=True)

In [11]:
disciplinary.drop('serial', axis=1,inplace=True)
disciplinary.drop('club', axis=1,inplace=True)
disciplinary.drop('position', axis=1,inplace=True)
disciplinary.drop('minutes_played', axis=1,inplace=True)
disciplinary.drop('match_played', axis=1,inplace=True)
disciplinary.drop('player_name', axis=1,inplace=True)

In [12]:
defending.drop('serial', axis=1,inplace=True)
defending.drop('club', axis=1,inplace=True)
defending.drop('position', axis=1,inplace=True)
defending.drop('match_played', axis=1,inplace=True)
defending.drop('player_name', axis=1,inplace=True)

In [13]:
attempts.drop('serial', axis=1,inplace=True)
attempts.drop('club', axis=1,inplace=True)
attempts.drop('position', axis=1,inplace=True)
attempts.drop('match_played', axis=1,inplace=True)
attempts.drop('player_name', axis=1,inplace=True)

In [14]:
attacking.drop('serial', axis=1,inplace=True)
attacking.drop('club', axis=1,inplace=True)
attacking.drop('position', axis=1,inplace=True)
attacking.drop('assists', axis=1,inplace=True)
attacking.drop('match_played', axis=1,inplace=True)
attacking.drop('player_name', axis=1,inplace=True)

In [15]:
stats = pd.merge(key_stats, goals, on="key", how='outer')
stats = pd.merge(stats, goalkeeping, on="key", how='outer')
stats = pd.merge(stats, distributon, on="key", how='outer')
stats = pd.merge(stats, disciplinary, on="key", how='outer')
stats = pd.merge(stats, defending, on="key", how='outer')
stats = pd.merge(stats, attempts, on="key", how='outer')
stats = pd.merge(stats, attacking, on="key", how='outer')

In [16]:
stats.shape

(747, 43)

In [17]:
stats.head()

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,right_foot,left_foot,...,t_won,t_lost,clearance_attempted,total_attempts,on_target,off_target,blocked,corner_taken,offsides,dribbles
key,,,,,,,,,,,,,,,,,,,,,
Courtois-Real Madrid-Goalkeeper,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vinícius Júnior-Real Madrid-Forward,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133,3.0,1.0,...,3.0,8.0,0.0,27.0,8.0,10.0,9.0,3.0,4.0,83.0
Benzema-Real Madrid-Forward,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,11.0,1.0,...,1.0,0.0,10.0,45.0,23.0,13.0,9.0,2.0,9.0,18.0
Modrić-Real Madrid-Midfielder,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,NaN,NaN,...,3.0,6.0,4.0,14.0,5.0,3.0,6.0,10.0,0.0,8.0
Éder Militão-Real Madrid-Defender,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4,NaN,NaN,...,6.0,13.0,32.0,9.0,4.0,5.0,0.0,NaN,NaN,NaN

## 1.1 Reducing dataset

In [19]:
pd.DataFrame(stats[stats['position'] == 'Goalkeeper']).shape[0], stats.shape[0]

(54, 747)

In [20]:
# Drop goalkeepers

stats.drop(stats[stats['position'] == 'Goalkeeper'].index, inplace = True)

In [21]:
pd.DataFrame(stats[stats['position'] == 'Goalkeeper']).shape[0], stats.shape[0]

(0, 693)

In [22]:
# Checking if there some player that hasn't have unique index

stats.index.is_unique

True

In [23]:
stats.columns

Index(['player_name', 'club', 'position', 'minutes_played', 'match_played',
       'goals', 'assists', 'distance_covered', 'right_foot', 'left_foot',
       'headers', 'others', 'inside_area', 'outside_areas', 'penalties',
       'saved', 'conceded', 'saved_penalties', 'cleansheets', 'punches made',
       'pass_accuracy', 'pass_attempted', 'pass_completed', 'cross_accuracy',
       'cross_attempted', 'cross_complted', 'freekicks_taken',
       'fouls_committed', 'fouls_suffered', 'red', 'yellow', 'balls_recoverd',
       'tackles', 't_won', 't_lost', 'clearance_attempted', 'total_attempts',
       'on_target', 'off_target', 'blocked', 'corner_taken', 'offsides',
       'dribbles'],
      dtype='object')

In [24]:
stats.shape

(693, 43)

In [25]:
output_att = ['goals', 'assists', 'balls_recoverd']

In [26]:
categorial_att = ['player_name', 'club', 'position']

In [27]:
potential_inputs = stats.columns
potential_inputs = [ elem for elem in potential_inputs if elem not in output_att]
potential_inputs = [ elem for elem in potential_inputs if elem not in categorial_att]

In [28]:
len(potential_inputs)

37

## 1.2 Droping uninformative attribute

In [29]:
attributes_to_drop = ['right_foot', 'left_foot', 'headers', 'others', 'inside_area', 'outside_areas', 'penalties', 
                     'saved', 'conceded', 'saved_penalties', 'cleansheets', 'punches made']

In [30]:
potential_inputs = [ elem for elem in potential_inputs if elem not in attributes_to_drop]

In [31]:
len(potential_inputs)

25

In [32]:
potential_inputs

['minutes_played',
 'match_played',
 'distance_covered',
 'pass_accuracy',
 'pass_attempted',
 'pass_completed',
 'cross_accuracy',
 'cross_attempted',
 'cross_complted',
 'freekicks_taken',
 'fouls_committed',
 'fouls_suffered',
 'red',
 'yellow',
 'tackles',
 't_won',
 't_lost',
 'clearance_attempted',
 'total_attempts',
 'on_target',
 'off_target',
 'blocked',
 'corner_taken',
 'offsides',
 'dribbles']

!!! Condition is that player played 200+ minutes and 3+ games

In [33]:
stats = stats.loc[(stats['minutes_played'] >= 200) & (stats['match_played'] >=3)][potential_inputs + output_att + categorial_att]

In [34]:
stats.shape

(441, 31)

In [35]:
stats.isna().sum(axis=0)

minutes_played           0
match_played             0
distance_covered         0
pass_accuracy            0
pass_attempted           0
pass_completed           0
cross_accuracy           0
cross_attempted          0
cross_complted           0
freekicks_taken          0
fouls_committed          8
fouls_suffered           8
red                      8
yellow                   8
tackles                  1
t_won                    1
t_lost                   1
clearance_attempted      1
total_attempts          34
on_target               34
off_target              34
blocked                 34
corner_taken           285
offsides               285
dribbles               285
goals                    0
assists                  0
balls_recoverd           1
player_name              0
club                     0
position                 0
dtype: int64

!!! All NA values are replaced with 0

In [36]:
stats = stats.fillna(0)

In [37]:
stats.isna().sum(axis=0).sum()

0

# 2. Filter method - F-test

These are output variables:
y1='goals'
y2='assists'
y3='balls_recoverd'

In [40]:
y1 = stats['goals']
y2 = stats['assists']
y3 = stats['balls_recoverd']
X = stats.drop(output_att + categorial_att, axis=1)

It will be done F-test for every output variable, and it will be calculated 10 the most informative attributes.

## 2.1. F-test : k-best=10 for 'goals'

In [41]:
selection10_goals = SelectKBest(f_regression, k=10)
selection10_goals.fit(X, y1)
X_filter_k10_goals = X.loc[:, selection10_goals.get_support()]

In [42]:
dfk10Atr_goals = pd.DataFrame({'Column' : X.columns.tolist(),
                   'Value True/False, k=10, goals' : selection10_goals.get_support().tolist()})
dfk10Atr_goals = dfk10Atr_goals.set_index('Column')
dfk10Atr_goals.style.applymap(color_false_red)

## 2.2. F-test : k-best=10 for 'assists'

In [43]:
selection10_assists = SelectKBest(f_regression, k=10)
selection10_assists.fit(X, y2)
X_filter_k10_assists = X.loc[:, selection10_assists.get_support()]

In [44]:
dfk10Atr_assists = pd.DataFrame({'Column' : X.columns.tolist(),
                   'Value True/False, k=10, assists' : selection10_assists.get_support().tolist()})
dfk10Atr_assists = dfk10Atr_assists.set_index('Column')
dfk10Atr_assists.style.applymap(color_false_red)

## 2.3 F-test : k-best=10 for 'balls_recoverd'

In [45]:
selection10_balls_recoverd = SelectKBest(f_regression, k=10)
selection10_balls_recoverd.fit(X, y3)
X_filter_k10_balls_recoverd = X.loc[:, selection10_balls_recoverd.get_support()]

In [46]:
dfk10Atr_balls_recoverd = pd.DataFrame({'Column' : X.columns.tolist(),
                   'Value True/False, k=10, balls_recoverd' : selection10_balls_recoverd.get_support().tolist()})
dfk10Atr_balls_recoverd = dfk10Atr_balls_recoverd.set_index('Column')
dfk10Atr_balls_recoverd.style.applymap(color_false_red)

## 2.4 All attributes

In [47]:
attr = pd.concat([dfk10Atr_goals, dfk10Atr_assists, dfk10Atr_balls_recoverd], axis=1)
attr_style = attr.style.apply(highlight, axis=None)
attr_style

In [48]:
# 4 attributes aren't important for any of outputs

((attr == True).sum(axis = 1) == 0).sum()

4

In [49]:
# cross_accuracy, fouls_committed, red, yellow aren't significant for any output

((attr == True).sum(axis = 1) == 0)

Column
minutes_played         False
match_played           False
distance_covered       False
pass_accuracy          False
pass_attempted         False
pass_completed         False
cross_accuracy          True
cross_attempted        False
cross_complted         False
freekicks_taken        False
fouls_committed         True
fouls_suffered         False
red                     True
yellow                  True
tackles                False
t_won                  False
t_lost                 False
clearance_attempted    False
total_attempts         False
on_target              False
off_target             False
blocked                False
corner_taken           False
offsides               False
dribbles               False
dtype: bool

In [50]:
# 12 attributes are important for 1 of 3 outputs

((attr == True).sum(axis = 1) == 1).sum()

12

In [51]:
attr[((attr == True).sum(axis = 1) == 1)]

,"Value True/False, k=10, goals","Value True/False, k=10, assists","Value True/False, k=10, balls_recoverd"
Column,,,
pass_accuracy,False,False,True
pass_attempted,False,False,True
pass_completed,False,False,True
cross_attempted,False,True,False
cross_complted,False,True,False
freekicks_taken,False,False,True
fouls_suffered,True,False,False
tackles,False,False,True
t_won,False,False,True
t_lost,False,False,True
clearance_attempted,False,False,True
corner_taken,False,True,False

In [52]:
# There is 9 attributes, that are important for 2 of 3 attributes

((attr == True).sum(axis = 1) == 2).sum()

9

In [53]:
attr[((attr == True).sum(axis = 1) == 2)]

,"Value True/False, k=10, goals","Value True/False, k=10, assists","Value True/False, k=10, balls_recoverd"
Column,,,
minutes_played,True,False,True
match_played,True,True,False
distance_covered,True,False,True
total_attempts,True,True,False
on_target,True,True,False
off_target,True,True,False
blocked,True,True,False
offsides,True,True,False
dribbles,True,True,False

In [54]:
# There is no a attribute, which is important for all outputs

((attr == True).sum(axis = 1) == 3).sum()

0

In [55]:
# These are attributes that are significant for 2 outputs and couple more that are significant by domain experts
# will be stay as potential input 

most_import_attr = attr[((attr == True).sum(axis = 1) == 2)].index.tolist() + ['pass_attempted', 'pass_completed',
                                                                            'tackles', 't_won','clearance_attempted']

In [56]:
# Potential inputs (reduced from 25 to 14 attributes)

len(most_import_attr)

14

In [57]:
# This variable has to be casted in float

stats['distance_covered'].dtypes

dtype('O')

In [58]:
stats['distance_covered'] = stats['distance_covered'].astype('float')

In [59]:
stats['distance_covered'].dtypes

dtype('float64')

Now, it is important to see correlation beetwen input and output

In [61]:
# correlation matrix of potential inputs

cor_mat = stats[most_import_attr + output_att].corr()

In [62]:
cor_mat[:-3]

,minutes_played,match_played,distance_covered,total_attempts,on_target,off_target,blocked,offsides,dribbles,pass_attempted,pass_completed,tackles,t_won,clearance_attempted,goals,assists,balls_recoverd
minutes_played,1.000000,0.807969,0.974492,0.417055,0.343557,0.393504,0.341439,0.309044,0.337539,0.764718,0.731634,0.397769,0.346974,0.430491,0.298835,0.329480,0.624387
match_played,0.807969,1.000000,0.827257,0.456575,0.399454,0.390228,0.386074,0.320580,0.350660,0.598814,0.568402,0.314177,0.257754,0.200073,0.346589,0.361396,0.393928
distance_covered,0.974492,0.827257,1.000000,0.412815,0.332536,0.381035,0.359922,0.312413,0.339037,0.745636,0.711411,0.421454,0.356392,0.342259,0.282390,0.346494,0.583418
total_attempts,0.417055,0.456575,0.412815,1.000000,0.904401,0.841967,0.814742,0.566612,0.560394,0.145092,0.113618,-0.123779,-0.175221,-0.255496,0.763548,0.458636,-0.204246
on_target,0.343557,0.399454,0.332536,0.904401,1.000000,0.620589,0.621596,0.596605,0.492141,0.058298,0.031520,-0.165740,-0.210733,-0.245112,0.871730,0.391349,-0.248369
off_target,0.393504,0.390228,0.381035,0.841967,0.620589,1.000000,0.556260,0.378663,0.438728,0.164118,0.139800,-0.054322,-0.101342,-0.151800,0.533036,0.348711,-0.106828
blocked,0.341439,0.386074,0.359922,0.814742,0.621596,0.556260,1.000000,0.448375,0.519334,0.181783,0.150880,-0.076731,-0.116580,-0.262344,0.470894,0.455347,-0.145216
offsides,0.309044,0.320580,0.312413,0.566612,0.596605,0.378663,0.448375,1.000000,0.527348,0.053040,0.023148,-0.092776,-0.139141,-0.150979,0.532825,0.463255,-0.160607
dribbles,0.337539,0.350660,0.339037,0.560394,0.492141,0.438728,0.519334,0.527348,1.000000,0.125456,0.095247,-0.056369,-0.090848,-0.165258,0.377497,0.641597,-0.079674
pass_attempted,0.764718,0.598814,0.745636,0.145092,0.058298,0.164118,0.181783,0.053040,0.125456,1.000000,0.995308,0.402898,0.389392,0.364796,0.020467,0.210440,0.727382
pass_completed,0.731634,0.568402,0.711411,0.113618,0.031520,0.139800,0.150880,0.023148,0.095247,0.995308,1.000000,0.394932,0.383672,0.358692,0.000526,0.174040,0.721278
tackles,0.397769,0.314177,0.421454,-0.123779,-0.165740,-0.054322,-0.076731,-0.092776,-0.056369,0.402898,0.394932,1.000000,0.885587,0.272702,-0.152331,-0.011739,0.548758
t_won,0.346974,0.257754,0.356392,-0.175221,-0.210733,-0.101342,-0.116580,-0.139141,-0.090848,0.389392,0.383672,0.885587,1.000000,0.329362,-0.183879,-0.057142,0.547225
clearance_attempted,0.430491,0.200073,0.342259,-0.255496,-0.245112,-0.151800,-0.262344,-0.150979,-0.165258,0.364796,0.358692,0.272702,0.329362,1.000000,-0.197745,-0.133367,0.667455

In [65]:
# potential inputs, which are correlated with minimum one output more than 0.5

cor_mat.loc[(abs(cor_mat['goals']) > 0.5) | (abs(cor_mat['assists']) > 0.5) | abs((cor_mat['balls_recoverd']) > 0.5),:][:-3]

,minutes_played,match_played,distance_covered,total_attempts,on_target,off_target,blocked,offsides,dribbles,pass_attempted,pass_completed,tackles,t_won,clearance_attempted,goals,assists,balls_recoverd
minutes_played,1.000000,0.807969,0.974492,0.417055,0.343557,0.393504,0.341439,0.309044,0.337539,0.764718,0.731634,0.397769,0.346974,0.430491,0.298835,0.329480,0.624387
distance_covered,0.974492,0.827257,1.000000,0.412815,0.332536,0.381035,0.359922,0.312413,0.339037,0.745636,0.711411,0.421454,0.356392,0.342259,0.282390,0.346494,0.583418
total_attempts,0.417055,0.456575,0.412815,1.000000,0.904401,0.841967,0.814742,0.566612,0.560394,0.145092,0.113618,-0.123779,-0.175221,-0.255496,0.763548,0.458636,-0.204246
on_target,0.343557,0.399454,0.332536,0.904401,1.000000,0.620589,0.621596,0.596605,0.492141,0.058298,0.031520,-0.165740,-0.210733,-0.245112,0.871730,0.391349,-0.248369
off_target,0.393504,0.390228,0.381035,0.841967,0.620589,1.000000,0.556260,0.378663,0.438728,0.164118,0.139800,-0.054322,-0.101342,-0.151800,0.533036,0.348711,-0.106828
offsides,0.309044,0.320580,0.312413,0.566612,0.596605,0.378663,0.448375,1.000000,0.527348,0.053040,0.023148,-0.092776,-0.139141,-0.150979,0.532825,0.463255,-0.160607
dribbles,0.337539,0.350660,0.339037,0.560394,0.492141,0.438728,0.519334,0.527348,1.000000,0.125456,0.095247,-0.056369,-0.090848,-0.165258,0.377497,0.641597,-0.079674
pass_attempted,0.764718,0.598814,0.745636,0.145092,0.058298,0.164118,0.181783,0.053040,0.125456,1.000000,0.995308,0.402898,0.389392,0.364796,0.020467,0.210440,0.727382
pass_completed,0.731634,0.568402,0.711411,0.113618,0.031520,0.139800,0.150880,0.023148,0.095247,0.995308,1.000000,0.394932,0.383672,0.358692,0.000526,0.174040,0.721278
tackles,0.397769,0.314177,0.421454,-0.123779,-0.165740,-0.054322,-0.076731,-0.092776,-0.056369,0.402898,0.394932,1.000000,0.885587,0.272702,-0.152331,-0.011739,0.548758
t_won,0.346974,0.257754,0.356392,-0.175221,-0.210733,-0.101342,-0.116580,-0.139141,-0.090848,0.389392,0.383672,0.885587,1.000000,0.329362,-0.183879,-0.057142,0.547225
clearance_attempted,0.430491,0.200073,0.342259,-0.255496,-0.245112,-0.151800,-0.262344,-0.150979,-0.165258,0.364796,0.358692,0.272702,0.329362,1.000000,-0.197745,-0.133367,0.667455

In [66]:
# potential inputs, which are correlated with all outputs less than 0.5

cor_mat.loc[(abs(cor_mat['goals']) < 0.5) & (abs(cor_mat['assists']) < 0.5) & abs((cor_mat['balls_recoverd']) < 0.5),:]

,minutes_played,match_played,distance_covered,total_attempts,on_target,off_target,blocked,offsides,dribbles,pass_attempted,pass_completed,tackles,t_won,clearance_attempted,goals,assists,balls_recoverd
match_played,0.807969,1.000000,0.827257,0.456575,0.399454,0.390228,0.386074,0.320580,0.350660,0.598814,0.568402,0.314177,0.257754,0.200073,0.346589,0.361396,0.393928
blocked,0.341439,0.386074,0.359922,0.814742,0.621596,0.556260,1.000000,0.448375,0.519334,0.181783,0.150880,-0.076731,-0.116580,-0.262344,0.470894,0.455347,-0.145216

In [67]:
# Variables 'match_played' and 'blocked' are dropped, because of weak correlation with outputs

most_import_attr.remove('match_played')
most_import_attr.remove('blocked')

Now, it will be observed mutual correlation beetwen input variables

In [65]:
# potential inputs that are mutually correlated with more than 0.9

(stats[most_import_attr].corr() > 0.9)

,minutes_played,distance_covered,total_attempts,on_target,off_target,offsides,dribbles,pass_attempted,pass_completed,tackles,t_won,clearance_attempted
minutes_played,True,True,False,False,False,False,False,False,False,False,False,False
distance_covered,True,True,False,False,False,False,False,False,False,False,False,False
total_attempts,False,False,True,True,False,False,False,False,False,False,False,False
on_target,False,False,True,True,False,False,False,False,False,False,False,False
off_target,False,False,False,False,True,False,False,False,False,False,False,False
offsides,False,False,False,False,False,True,False,False,False,False,False,False
dribbles,False,False,False,False,False,False,True,False,False,False,False,False
pass_attempted,False,False,False,False,False,False,False,True,True,False,False,False
pass_completed,False,False,False,False,False,False,False,True,True,False,False,False
tackles,False,False,False,False,False,False,False,False,False,True,False,False
t_won,False,False,False,False,False,False,False,False,False,False,True,False
clearance_attempted,False,False,False,False,False,False,False,False,False,False,False,True

There is strong correlation with potential inputs:  

'minutes_played' and 'distance_covered' -> 'minutes_played'  
'total_attempts' and 'on_target' -> 'on_target'  
'pass_attempted' and 'pass_completed' -> 'pass_completed'  

Also, correlation less than 0.9, but still huge:  
'tackles' and 't_won' -> 't_won'

In [69]:
# These potential inputs that are mutually strong correlated are dropped

most_import_attr.remove('distance_covered')
most_import_attr.remove('total_attempts')
most_import_attr.remove('pass_attempted')
most_import_attr.remove('tackles')

In [70]:
most_import_attr

['minutes_played',
 'on_target',
 'off_target',
 'offsides',
 'dribbles',
 'pass_completed',
 't_won',
 'clearance_attempted']

In [71]:
# Correlation matrix of inputs and otputs

round(stats[most_import_attr + output_att].corr().iloc[:-3:], 3)

,minutes_played,on_target,off_target,offsides,dribbles,pass_completed,t_won,clearance_attempted,goals,assists,balls_recoverd
minutes_played,1.000,0.344,0.394,0.309,0.338,0.732,0.347,0.430,0.299,0.329,0.624
on_target,0.344,1.000,0.621,0.597,0.492,0.032,-0.211,-0.245,0.872,0.391,-0.248
off_target,0.394,0.621,1.000,0.379,0.439,0.140,-0.101,-0.152,0.533,0.349,-0.107
offsides,0.309,0.597,0.379,1.000,0.527,0.023,-0.139,-0.151,0.533,0.463,-0.161
dribbles,0.338,0.492,0.439,0.527,1.000,0.095,-0.091,-0.165,0.377,0.642,-0.080
pass_completed,0.732,0.032,0.140,0.023,0.095,1.000,0.384,0.359,0.001,0.174,0.721
t_won,0.347,-0.211,-0.101,-0.139,-0.091,0.384,1.000,0.329,-0.184,-0.057,0.547
clearance_attempted,0.430,-0.245,-0.152,-0.151,-0.165,0.359,0.329,1.000,-0.198,-0.133,0.667

## 2.5. Domain knowledge for selecting inputs

In [72]:
# These to variables are dropped, because they are not to importnat in reality

most_import_attr.remove('off_target')
most_import_attr.remove('offsides')

In [73]:
most_import_attr

['minutes_played',
 'on_target',
 'dribbles',
 'pass_completed',
 't_won',
 'clearance_attempted']

In [74]:
# Attributes, which have number 0 as value

(stats[categorial_att + most_import_attr + output_att] == 0).sum()

player_name              0
club                     0
position                 0
minutes_played           0
on_target              148
dribbles               295
pass_completed           0
t_won                   97
clearance_attempted     41
goals                  279
assists                285
balls_recoverd           1
dtype: int64

In [76]:
# Number of players per club

stats[categorial_att + most_import_attr + output_att].groupby('club').count()['player_name']

club
Ajax                12
Atalanta            14
Atlético            18
Barcelona           12
Bayern              15
Benfica             14
Beşiktaş            13
Chelsea             17
Club Brugge         10
Dortmund            10
Dynamo Kyiv         10
Inter               12
Juventus            15
LOSC                15
Leipzig             13
Liverpool           19
Malmö               13
Man. City           17
Man. United         16
Milan               14
Paris               14
Porto               12
Real Madrid         15
Salzburg            14
Sevilla             13
Shakhtar Donetsk    13
Sheriff             11
Sporting CP         15
Villarreal          17
Wolfsburg           13
Young Boys          12
Zenit               13
Name: player_name, dtype: int64

In [78]:
# Shape of final dataset

stats[categorial_att + most_import_attr + output_att].shape

(441, 12)

## 2.6 Final preparation of dataset

It was seen that some players have the same name, so for that players name have to be changde, For example, it can be addded lastnam, etc. This is important, because player name will be the key value.

In [82]:
final_stats = stats[categorial_att + most_import_attr + output_att]

In [83]:
final_stats

,player_name,club,position,minutes_played,on_target,dribbles,pass_completed,t_won,clearance_attempted,goals,assists,balls_recoverd
key,,,,,,,,,,,,
Vinícius Júnior-Real Madrid-Forward,Vinícius Júnior,Real Madrid,Forward,1199,8.0,83.0,377.0,3.0,0.0,4,6,29.0
Benzema-Real Madrid-Forward,Benzema,Real Madrid,Forward,1106,23.0,18.0,433.0,1.0,10.0,15,1,6.0
Modrić-Real Madrid-Midfielder,Modrić,Real Madrid,Midfielder,1077,5.0,8.0,723.0,3.0,4.0,0,4,39.0
Éder Militão-Real Madrid-Defender,Éder Militão,Real Madrid,Defender,1076,4.0,0.0,563.0,6.0,32.0,0,0,76.0
Alaba-Real Madrid-Defender,Alaba,Real Madrid,Defender,1040,1.0,0.0,606.0,12.0,28.0,1,0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...
Bornauw-Wolfsburg-Defender,Bornauw,Wolfsburg,Defender,204,0.0,0.0,68.0,1.0,10.0,0,0,15.0
Neres-Ajax-Forward,Neres,Ajax,Forward,203,3.0,0.0,91.0,0.0,0.0,1,0,3.0
Haaland-Dortmund-Forward,Haaland,Dortmund,Forward,203,7.0,0.0,27.0,0.0,4.0,3,0,5.0
Bruno Tabata-Sporting CP-Midfielder,Bruno Tabata,Sporting CP,Midfielder,201,1.0,2.0,58.0,0.0,2.0,1,1,3.0
Delaney-Sevilla-Midfielder,Delaney,Sevilla,Midfielder,200,0.0,0.0,61.0,2.0,3.0,0,0,9.0

In [84]:
final_stats['player_name'].nunique()

435

In [85]:
# Trying to find some other key

#final_stats['new_att'] = final_stats[['player_name', 'club']].agg('-'.join, axis=1)
#final_stats['new_att'].nunique()

In [86]:
final_stats[final_stats['player_name'].duplicated()]

,player_name,club,position,minutes_played,on_target,dribbles,pass_completed,t_won,clearance_attempted,goals,assists,balls_recoverd
key,,,,,,,,,,,,
Martínez-Inter-Forward,Martínez,Inter,Forward,587,7.0,0.0,97.0,4.0,0.0,1,0,13.0
Danilo-Paris-Midfielder,Danilo,Paris,Midfielder,362,0.0,0.0,185.0,2.0,10.0,0,0,15.0
João Mário-Porto-Forward,João Mário,Porto,Forward,351,0.0,0.0,95.0,0.0,6.0,0,0,21.0
Fernando-Shakhtar Donetsk-Midfielder,Fernando,Shakhtar Donetsk,Midfielder,350,5.0,0.0,63.0,0.0,1.0,2,0,6.0
Camara-Young Boys-Defender,Camara,Young Boys,Defender,347,1.0,0.0,185.0,3.0,11.0,0,0,22.0
Herrera-Atlético-Midfielder,Herrera,Atlético,Midfielder,226,0.0,0.0,102.0,1.0,1.0,0,0,20.0

Some players's name has to be changed, in order to make attribute 'player_name' as attribute with unique values
The change is juts adding some part or full name to player's name

In [89]:
#final_stats.to_csv('C:/Users/Zbook G3/Desktop/stats.csv')

In [90]:
final_stats = pd.read_csv('D:/Luka Sve/Strucni radovi/DEA/stats.csv')

In [91]:
# There is no diplicate values for attribute 'player_name'

final_stats[final_stats['player_name'].duplicated()]

Empty DataFrame
Columns: [key, player_name, club, position, minutes_played, on_target, dribbles, pass_completed, t_won, clearance_attempted, goals, assists, balls_recoverd]
Index: []

In [92]:
# Index will be attribute player_name

final_stats = final_stats.set_index('player_name')

In [93]:
# 'player_name' has all values unique

final_stats.index.is_unique

True

In [94]:
# 'key' is dropped, because it is not index anymore

final_stats.drop('key', axis=1, inplace=True)

In [95]:
final_stats

,club,position,minutes_played,on_target,dribbles,pass_completed,t_won,clearance_attempted,goals,assists,balls_recoverd
player_name,,,,,,,,,,,
Vinícius Júnior,Real Madrid,Forward,1199,8,83,377,3,0,4,6,29
Benzema,Real Madrid,Forward,1106,23,18,433,1,10,15,1,6
Modrić,Real Madrid,Midfielder,1077,5,8,723,3,4,0,4,39
Éder Militão,Real Madrid,Defender,1076,4,0,563,6,32,0,0,76
Alaba,Real Madrid,Defender,1040,1,0,606,12,28,1,0,49
...,...,...,...,...,...,...,...,...,...,...,...
Bornauw,Wolfsburg,Defender,204,0,0,68,1,10,0,0,15
Neres,Ajax,Forward,203,3,0,91,0,0,1,0,3
Haaland,Dortmund,Forward,203,7,0,27,0,4,3,0,5
Bruno Tabata,Sporting CP,Midfielder,201,1,2,58,0,2,1,1,3
Delaney,Sevilla,Midfielder,200,0,0,61,2,3,0,0,9

In [96]:
# Sorting by attribute 'club', because of the nicer overview of the dataframe

final_stats.sort_values(by=['club', 'position'], axis=0, ascending=True, inplace=True)

In [97]:
# 441 plates, 32 clubs, 11 attributes (2 categorical, 6 inputs, 3 outputs)

final_stats

,club,position,minutes_played,on_target,dribbles,pass_completed,t_won,clearance_attempted,goals,assists,balls_recoverd
player_name,,,,,,,,,,,
Lisandro Martínez,Ajax,Defender,720,2,3,633,2,19,0,1,53
Mazraoui,Ajax,Defender,661,3,13,338,10,9,0,2,40
Blind,Ajax,Defender,572,2,8,368,4,8,1,1,32
Haller,Ajax,Forward,668,15,9,134,2,5,11,1,10
Tadić,Ajax,Forward,630,3,13,231,0,1,2,2,12
...,...,...,...,...,...,...,...,...,...,...,...
Barrios,Zenit,Midfielder,540,0,0,282,7,13,0,0,41
Wendel,Zenit,Midfielder,484,4,0,274,4,6,1,0,22
Claudinho,Zenit,Midfielder,460,4,0,229,1,3,2,0,20
Sutormin,Zenit,Midfielder,293,2,0,145,0,3,1,0,5
Kuzyaev,Zenit,Midfielder,257,1,0,71,0,5,1,0,10

In [98]:
# Renaming attributes, because of better understanding of them

final_stats.rename(columns = {'t_won':'tackles_won', 'on_target':'shots_on_target'}, inplace = True)

In [99]:
final_stats

,club,position,minutes_played,shots_on_target,dribbles,pass_completed,tackles_won,clearance_attempted,goals,assists,balls_recoverd
player_name,,,,,,,,,,,
Lisandro Martínez,Ajax,Defender,720,2,3,633,2,19,0,1,53
Mazraoui,Ajax,Defender,661,3,13,338,10,9,0,2,40
Blind,Ajax,Defender,572,2,8,368,4,8,1,1,32
Haller,Ajax,Forward,668,15,9,134,2,5,11,1,10
Tadić,Ajax,Forward,630,3,13,231,0,1,2,2,12
...,...,...,...,...,...,...,...,...,...,...,...
Barrios,Zenit,Midfielder,540,0,0,282,7,13,0,0,41
Wendel,Zenit,Midfielder,484,4,0,274,4,6,1,0,22
Claudinho,Zenit,Midfielder,460,4,0,229,1,3,2,0,20
Sutormin,Zenit,Midfielder,293,2,0,145,0,3,1,0,5
Kuzyaev,Zenit,Midfielder,257,1,0,71,0,5,1,0,10

In [100]:
# Making new csv file with final dataset

#final_stats.to_csv('D:/Luka Sve/Strucni radovi/DEA/final_stats.csv')

In [102]:
# dataset grouped by clubs

final_stats.groupby('club').sum()

,minutes_played,shots_on_target,dribbles,pass_completed,tackles_won,clearance_attempted,goals,assists,balls_recoverd
club,,,,,,,,,
Ajax,6722,51,95,3536,39,78,21,15,293
Atalanta,4945,23,55,2164,29,90,10,10,265
Atlético,8368,27,47,2580,50,169,9,7,396
Barcelona,4356,6,0,2509,36,44,1,1,215
Bayern,8525,69,144,4968,37,83,29,22,414
Benfica,8183,31,51,2483,70,188,12,10,360
Beşiktaş,4076,10,4,1501,36,65,3,2,207
Chelsea,8582,52,78,5129,40,82,20,16,371
Club Brugge,4573,22,34,1339,23,92,5,4,228
Dortmund,3967,28,39,1922,14,56,10,7,228
Dynamo Kyiv,4454,15,8,1629,24,90,1,1,201
Inter,6241,36,24,2934,41,108,8,5,282
Juventus,6480,27,22,3283,37,108,8,6,323
LOSC,7278,21,20,2593,55,142,7,3,381
Leipzig,4721,32,19,1822,31,81,15,9,235
Liverpool,10817,78,164,6359,52,144,27,20,543
Malmö,4764,7,19,1454,26,137,1,1,180
Man. City,10836,65,144,6423,37,111,27,23,441
Man. United,6124,33,14,2982,37,107,11,10,279
Milan,4693,13,46,1662,31,107,3,5,250
Paris,6775,39,73,3752,49,122,15,7,255
Porto,4135,13,7,1328,25,88,2,2,222
Real Madrid,11875,65,165,6057,75,182,28,21,503
Salzburg,7024,36,49,2068,42,148,9,5,360
Sevilla,4531,19,17,2181,13,62,5,3,237
Shakhtar Donetsk,4521,15,5,2562,13,55,2,1,174
Sheriff,5000,16,21,1087,35,177,5,5,211
Sporting CP,6527,28,44,2132,47,124,14,9,263
Villarreal,10433,43,74,3490,52,266,19,15,446
Wolfsburg,4758,11,1,1450,22,144,5,3,237
Young Boys,4697,24,45,1767,29,65,7,4,246
Zenit,5047,25,26,2152,32,127,8,8,224

In [108]:
final_stats.groupby('club').count().iloc[:,0]

club
Ajax                12
Atalanta            14
Atlético            18
Barcelona           12
Bayern              15
Benfica             14
Beşiktaş            13
Chelsea             17
Club Brugge         10
Dortmund            10
Dynamo Kyiv         10
Inter               12
Juventus            15
LOSC                15
Leipzig             13
Liverpool           19
Malmö               13
Man. City           17
Man. United         16
Milan               14
Paris               14
Porto               12
Real Madrid         15
Salzburg            14
Sevilla             13
Shakhtar Donetsk    13
Sheriff             11
Sporting CP         15
Villarreal          17
Wolfsburg           13
Young Boys          12
Zenit               13
Name: position, dtype: int64